# Generated by Django 3.0.6 on 2020-06-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('fathers_name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Select Gender', max_length=6)),
                ('date_of_birth', models.DateField()),
                ('last_class_passed', models.CharField(choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX')], max_length=4)),
                ('year_of_passing', models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2019, max_length=4, verbose_name='year')),
                ('current_class', models.CharField(choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX')], max_length=4)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=4)),
                ('roll', models.PositiveSmallIntegerField()),
                ('annual_family_income', models.PositiveIntegerField()),
                ('village', models.CharField(max_length=25)),
                ('post_office', models.CharField(max_length=25)),
                ('sub_division', models.CharField(max_length=25)),
                ('block', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=15)),
                ('pincode', models.PositiveIntegerField()),
                ('mobile_number', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=45)),
                ('branch_name', models.CharField(max_length=25)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=30)),
                ('sub_caste', models.CharField(max_length=25)),
            ],
        ),
    ]
