# Generated by Django 3.0.6 on 2020-06-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.CharField(choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_class_passed',
            field=models.CharField(choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_passing',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2019, verbose_name='year'),
        ),
    ]
