# Generated by Django 3.0.6 on 2020-06-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBC', '0002_auto_20200603_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='current_class',
            new_name='present_class',
        ),
    ]
