# Generated by Django 3.0.6 on 2020-06-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBC', '0003_auto_20200607_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_passing',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2019, verbose_name='year'),
        ),
    ]
