# Generated by Django 3.0.6 on 2020-06-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBC', '0004_auto_20200607_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='annual_family_income',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
