# Generated by Django 3.0.6 on 2020-06-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBC', '0005_auto_20200607_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='district',
        ),
    ]
